name: docker
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
            git submodule init
            git submodule update
      - name: Docker Build
        run: cd scripts && docker build -t r2ghidra . -f Dockerfile.buster && cd ..
      - name: Build and Test
        run: docker run --rm -v "`pwd`:/build" -t r2ghidra /bin/bash -c "cd /build && scripts/ci-script"

